#!/bin/sh
# postinst script for thinkhdd
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    configure)
    if hash systemctl 2>/dev/null;
      then
        systemctl enable thinkhdd;
        systemctl start thinkhdd;
    fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    if hash systemctl 2>/dev/null;
      then
        systemctl disable thinkhdd;
        systemctl stop thinkhdd;
    fi
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

exit 0
